FORMAT: 1A

# deploy.io
Is a service that will publish code from GitHub to a specfied server.
TODO: Create debs and Maybe talk about apt-get repo
It will also allow you to run post deploy scripts.

# Deployment repos
Repositories from GitHub that are allowed to be deployed via the **deploy.io API**

## Repos Collection [/{user}]
### List all repos for that user or organization [GET]
+ Parameters
    + user (required, string, `chris`) ... String `name` of the user to perform action with. Has example value.
    
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Repo 1"
        }, {
          "id": 2, "title": "Repo 2"
        }]

## Repo [/{user}/{repo}]
A single repo object with all its details

### Retrieve a single repo [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Create a new deployment configuration for the specified repo [POST]
+ Parameters
    + user (required, string, `chris`) ... String `name` of the user to perform action with. Has example value.
    + repo (required, string, `deploy.io`) ... String `repo` of the repo to perform action with. Has example value.
    
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

### Remove a Repo configuration [DELETE]
+ Response 204
